In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#from pandasql import sqldf

df_article = pd.read_csv('articles.csv')
df_article

,article_id,product_code,prod_name,product_type_no,product_type_name,product_group_name,graphical_appearance_no,graphical_appearance_name,colour_group_code,colour_group_name,...,department_name,index_code,index_name,index_group_no,index_group_name,section_no,section_name,garment_group_no,garment_group_name,detail_desc
0,108775015,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
1,108775044,108775,Strap top,253,Vest top,Garment Upper body,1010016,Solid,10,White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
2,108775051,108775,Strap top (1),253,Vest top,Garment Upper body,1010017,Stripe,11,Off White,...,Jersey Basic,A,Ladieswear,1,Ladieswear,16,Womens Everyday Basics,1002,Jersey Basic,Jersey top with narrow shoulder straps.
3,110065001,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,9,Black,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
4,110065002,110065,OP T-shirt (Idro),306,Bra,Underwear,1010016,Solid,10,White,...,Clean Lingerie,B,Lingeries/Tights,1,Ladieswear,61,Womens Lingerie,1017,"Under-, Nightwear","Microfibre T-shirt bra with underwired, moulde..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105537,953450001,953450,5pk regular Placement1,302,Socks,Socks & Tights,1010014,Placement print,9,Black,...,Socks Bin,F,Menswear,3,Menswear,26,Men Underwear,1021,Socks and Tights,Socks in a fine-knit cotton blend with a small...
105538,953763001,953763,SPORT Malaga tank,253,Vest top,Garment Upper body,1010016,Solid,9,Black,...,Jersey,A,Ladieswear,1,Ladieswear,2,H&M+,1005,Jersey Fancy,Loose-fitting sports vest top in ribbed fast-d...
105539,956217002,956217,Cartwheel dress,265,Dress,Garment Full body,1010016,Solid,9,Black,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,"Short, A-line dress in jersey with a round nec..."
105540,957375001,957375,CLAIRE HAIR CLAW,72,Hair clip,Accessories,1010016,Solid,9,Black,...,Small Accessories,D,Divided,2,Divided,52,Divided Accessories,1019,Accessories,Large plastic hair claw.
105541,959461001,959461,Lounge dress,265,Dress,Garment Full body,1010016,Solid,11,Off White,...,Jersey,A,Ladieswear,1,Ladieswear,18,Womens Trend,1005,Jersey Fancy,Calf-length dress in ribbed jersey made from a...

In [2]:
df_article.columns

Index(['article_id', 'product_code', 'prod_name', 'product_type_no',
       'product_type_name', 'product_group_name', 'graphical_appearance_no',
       'graphical_appearance_name', 'colour_group_code', 'colour_group_name',
       'perceived_colour_value_id', 'perceived_colour_value_name',
       'perceived_colour_master_id', 'perceived_colour_master_name',
       'department_no', 'department_name', 'index_code', 'index_name',
       'index_group_no', 'index_group_name', 'section_no', 'section_name',
       'garment_group_no', 'garment_group_name', 'detail_desc'],
      dtype='object')

Dropping the columns that are not needed for the model training

In [3]:
df_art = df_article

df_art.drop(['product_code', 'prod_name', 'product_type_no',
       'graphical_appearance_no', 'colour_group_code', 'colour_group_name',
       'perceived_colour_value_id', 'perceived_colour_master_id', 'perceived_colour_master_name',
       'department_no', 'department_name', 'index_code', 'index_name',
       'index_group_no', 'section_no', 'garment_group_no', 'detail_desc'], inplace=True, axis=1)

df_art

,article_id,product_type_name,product_group_name,graphical_appearance_name,perceived_colour_value_name,index_group_name,section_name,garment_group_name
0,108775015,Vest top,Garment Upper body,Solid,Dark,Ladieswear,Womens Everyday Basics,Jersey Basic
1,108775044,Vest top,Garment Upper body,Solid,Light,Ladieswear,Womens Everyday Basics,Jersey Basic
2,108775051,Vest top,Garment Upper body,Stripe,Dusty Light,Ladieswear,Womens Everyday Basics,Jersey Basic
3,110065001,Bra,Underwear,Solid,Dark,Ladieswear,Womens Lingerie,"Under-, Nightwear"
4,110065002,Bra,Underwear,Solid,Light,Ladieswear,Womens Lingerie,"Under-, Nightwear"
...,...,...,...,...,...,...,...,...
105537,953450001,Socks,Socks & Tights,Placement print,Dark,Menswear,Men Underwear,Socks and Tights
105538,953763001,Vest top,Garment Upper body,Solid,Dark,Ladieswear,H&M+,Jersey Fancy
105539,956217002,Dress,Garment Full body,Solid,Dark,Ladieswear,Womens Trend,Jersey Fancy
105540,957375001,Hair clip,Accessories,Solid,Dark,Divided,Divided Accessories,Accessories
105541,959461001,Dress,Garment Full body,Solid,Dusty Light,Ladieswear,Womens Trend,Jersey Fancy

Looking at the cardinallity of the categorical columns and replacing the rare categories with 'other'

In [4]:
df_art['graphical_appearance_name'].value_counts()

Solid                  49747
All over pattern       17165
Melange                 5938
Stripe                  4990
Denim                   4842
Front print             3215
Placement print         3098
Check                   2178
Colour blocking         1830
Lace                    1513
Other structure         1502
Application/3D          1341
Embroidery              1165
Mixed solid/pattern     1132
Glittering/Metallic      958
Jacquard                 830
Sequin                   806
Dot                      681
Treatment                586
Other pattern            515
Contrast                 376
Metallic                 346
Chambray                 322
Slub                     153
Transparent               86
Mesh                      86
Neps                      66
Unknown                   52
Argyle                    15
Hologram                   8
Name: graphical_appearance_name, dtype: int64

In [5]:
df_art['product_group_name'].value_counts()

Garment Upper body       42741
Garment Lower body       19812
Garment Full body        13292
Accessories              11158
Underwear                 5490
Shoes                     5283
Swimwear                  3127
Socks & Tights            2442
Nightwear                 1899
Unknown                    121
Underwear/nightwear         54
Cosmetic                    49
Bags                        25
Items                       17
Furniture                   13
Garment and Shoe care        9
Stationery                   5
Interior textile             3
Fun                          2
Name: product_group_name, dtype: int64

In [6]:
df_art['section_name'].value_counts()

Womens Everyday Collection        7295
Divided Collection                7124
Baby Essentials & Complements     4932
Kids Girl                         4469
Young Girl                        3899
Womens Lingerie                   3598
Girls Underwear & Basics          3490
Womens Tailoring                  3376
Kids Boy                          3328
Womens Small accessories          3270
Womens Casual                     2725
Kids Outerwear                    2665
Womens Trend                      2622
Divided Projects                  2364
Young Boy                         2352
H&M+                              2337
Men Underwear                     2322
Mama                              2266
Kids & Baby Shoes                 2142
Boys Underwear & Basics           2034
Womens Shoes                      2026
Ladies H&M Sport                  1894
Womens Swimwear, beachwear        1839
Contemporary Smart                1778
Baby Girl                         1760
Divided Accessories               1732
Kids Accessories, Swimwear & D    1731
Divided Basics                    1723
Baby Boy                          1717
Womens Big accessories            1665
Womens Everyday Basics            1581
Womens Nightwear, Socks & Tigh    1566
Contemporary Casual               1560
Contemporary Street               1490
Men Suits & Tailoring             1428
Men Accessories                   1337
Womens Premium                    1270
Ladies Denim                      1101
Divided Selected                   991
Men H&M Sport                      872
Womens Jackets                     829
Special Collections                682
Men Shoes                          645
Mens Outerwear                     629
Kids Sports                        626
Collaborations                     559
Denim Men                          521
Men Edition                        330
Men Project                        298
Divided Asia keys                  280
Kids Local Relevance               192
Men Other 2                        190
Divided Complements Other           35
EQ Divided                          26
Men Other                           25
Ladies Other                         4
Name: section_name, dtype: int64

In [7]:
df_art['garment_group_name'].value_counts()

Jersey Fancy                     21445
Accessories                      11519
Jersey Basic                      8126
Knitwear                          7490
Under-, Nightwear                 7441
Trousers                          6727
Blouses                           5838
Shoes                             5145
Dresses Ladies                    4874
Outdoor                           4501
Unknown                           3873
Trousers Denim                    3100
Swimwear                          2787
Socks and Tights                  2272
Shirts                            2116
Woven/Jersey/Knitted mix Baby     1965
Shorts                            1559
Dresses/Skirts girls              1541
Skirts                            1254
Special Offers                    1061
Dressed                            908
Name: garment_group_name, dtype: int64

In [8]:
df_art['product_type_name'].value_counts().iloc[:20]

Trousers            11169
Dress               10362
Sweater              9302
T-shirt              7904
Top                  4155
Blouse               3979
Jacket               3940
Shorts               3939
Shirt                3405
Vest top             2991
Underwear bottom     2748
Skirt                2696
Hoodie               2356
Bra                  2212
Socks                1889
Leggings/Tights      1878
Sneakers             1621
Cardigan             1550
Hat/beanie           1349
Garment Set          1320
Name: product_type_name, dtype: int64

In [9]:
temp = df_art['graphical_appearance_name'].value_counts() <= 2000
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_graphical_appearance"] = df_art["graphical_appearance_name"].apply(lambda x : 'other' if x in mask else x)

In [10]:
df_art['modified_graphical_appearance'].value_counts()

Solid               49747
All over pattern    17165
other               14369
Melange              5938
Stripe               4990
Denim                4842
Front print          3215
Placement print      3098
Check                2178
Name: modified_graphical_appearance, dtype: int64

In [11]:
temp = df_art['product_group_name'].value_counts() <= 2000
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_product_group"] = df_art["product_group_name"].apply(lambda x : 'other' if x in mask else x)

df_art['modified_product_group'].value_counts()

Garment Upper body    42741
Garment Lower body    19812
Garment Full body     13292
Accessories           11158
Underwear              5490
Shoes                  5283
Swimwear               3127
Socks & Tights         2442
other                  2197
Name: modified_product_group, dtype: int64

In [12]:
temp = df_art['section_name'].value_counts() <= 3328
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_section"] = df_art["section_name"].apply(lambda x : 'other' if x in mask else x)

df_art['modified_section'].value_counts()

other                            67359
Womens Everyday Collection        7295
Divided Collection                7124
Baby Essentials & Complements     4932
Kids Girl                         4469
Young Girl                        3899
Womens Lingerie                   3598
Girls Underwear & Basics          3490
Womens Tailoring                  3376
Name: modified_section, dtype: int64

In [13]:
temp = df_art['garment_group_name'].value_counts() <= 4874
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_garment_group"] = df_art["garment_group_name"].apply(lambda x : 'other' if x in mask else x)

df_art['modified_garment_group'].value_counts()

other                31811
Jersey Fancy         21445
Accessories          11519
Jersey Basic          8126
Knitwear              7490
Under-, Nightwear     7441
Trousers              6727
Blouses               5838
Shoes                 5145
Name: modified_garment_group, dtype: int64

In [14]:
#keeping 20 most frequent
temp = df_art['product_type_name'].value_counts() <= 1320
temp = temp.loc[temp]
mask = set(temp.index)
df_art["modified_product_type"] = df_art["product_type_name"].apply(lambda x : 'other' if x in mask else x)

df_art['modified_product_type'].value_counts()

other               26097
Trousers            11169
Dress               10362
Sweater              9302
T-shirt              7904
Top                  4155
Blouse               3979
Jacket               3940
Shorts               3939
Shirt                3405
Vest top             2991
Underwear bottom     2748
Skirt                2696
Hoodie               2356
Bra                  2212
Socks                1889
Leggings/Tights      1878
Sneakers             1621
Cardigan             1550
Hat/beanie           1349
Name: modified_product_type, dtype: int64

In [15]:
df_art.columns

Index(['article_id', 'product_type_name', 'product_group_name',
       'graphical_appearance_name', 'perceived_colour_value_name',
       'index_group_name', 'section_name', 'garment_group_name',
       'modified_graphical_appearance', 'modified_product_group',
       'modified_section', 'modified_garment_group', 'modified_product_type'],
      dtype='object')

In [16]:
df_art.drop(['graphical_appearance_name', 'product_group_name', 'section_name', 'garment_group_name', 'product_type_name'], inplace=True, axis=1)

df_art

,article_id,perceived_colour_value_name,index_group_name,modified_graphical_appearance,modified_product_group,modified_section,modified_garment_group,modified_product_type
0,108775015,Dark,Ladieswear,Solid,Garment Upper body,other,Jersey Basic,Vest top
1,108775044,Light,Ladieswear,Solid,Garment Upper body,other,Jersey Basic,Vest top
2,108775051,Dusty Light,Ladieswear,Stripe,Garment Upper body,other,Jersey Basic,Vest top
3,110065001,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",Bra
4,110065002,Light,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",Bra
...,...,...,...,...,...,...,...,...
105537,953450001,Dark,Menswear,Placement print,Socks & Tights,other,other,Socks
105538,953763001,Dark,Ladieswear,Solid,Garment Upper body,other,Jersey Fancy,Vest top
105539,956217002,Dark,Ladieswear,Solid,Garment Full body,other,Jersey Fancy,Dress
105540,957375001,Dark,Divided,Solid,Accessories,other,Accessories,other
105541,959461001,Dusty Light,Ladieswear,Solid,Garment Full body,other,Jersey Fancy,Dress

# Customers Data Exploration

In [17]:
df_customer = pd.read_csv('customers.csv')
df_customer

,customer_id,FN,Active,club_member_status,fashion_news_frequency,age,postal_code
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,NaN,ACTIVE,NONE,49.0,52043ee2162cf5aa7ee79974281641c6f11a68d276429a...
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,NaN,ACTIVE,NONE,25.0,2973abc54daa8a5f8ccfe9362140c63247c5eee03f1d93...
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,NaN,ACTIVE,NONE,24.0,64f17e6a330a85798e4998f62d0930d14db8db1c054af6...
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,NaN,ACTIVE,NONE,54.0,5d36574f52495e81f019b680c843c443bd343d5ca5b1c2...
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,1.0,ACTIVE,Regularly,52.0,25fa5ddee9aac01b35208d01736e57942317d756b32ddd...
...,...,...,...,...,...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,NaN,NaN,ACTIVE,NONE,24.0,7aa399f7e669990daba2d92c577b52237380662f36480b...
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,NaN,NaN,ACTIVE,NONE,21.0,3f47f1279beb72215f4de557d950e0bfa73789d24acb5e...
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,1.0,1.0,ACTIVE,Regularly,21.0,4563fc79215672cd6a863f2b4bf56b8f898f2d96ed590e...
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,1.0,1.0,ACTIVE,Regularly,18.0,8892c18e9bc3dca6aa4000cb8094fc4b51ee8db2ed14d7...
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,NaN,NaN,PRE-CREATE,NONE,65.0,0a1a03306fb2f62164c2a439b38c0caa64b40deaae8687...

In [18]:
df_customer.columns

Index(['customer_id', 'FN', 'Active', 'club_member_status',
       'fashion_news_frequency', 'age', 'postal_code'],
      dtype='object')

In [19]:
df_cust = df_customer

df_cust.drop(['FN', 'fashion_news_frequency', 'postal_code'], inplace=True, axis=1)

df_cust

,customer_id,Active,club_member_status,age
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,NaN,ACTIVE,49.0
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,NaN,ACTIVE,25.0
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,NaN,ACTIVE,24.0
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,NaN,ACTIVE,54.0
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,ACTIVE,52.0
...,...,...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,NaN,ACTIVE,24.0
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,NaN,ACTIVE,21.0
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,1.0,ACTIVE,21.0
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,1.0,ACTIVE,18.0
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,NaN,PRE-CREATE,65.0

In [20]:
df_cust['club_member_status'] = df_cust['club_member_status'].fillna('N/A')

In [21]:
df_cust['Active'] = df_cust['Active'].fillna(0)
df_cust["age"] = df_cust["age"].fillna(df_cust["age"].mean())

In [22]:
df_cust = pd.concat([df_cust.drop(columns=["club_member_status"]), pd.get_dummies(df_cust["club_member_status"])], axis=1)

In [126]:
df_cust

,customer_id,Active,age,ACTIVE,LEFT CLUB,N/A,PRE-CREATE
0,00000dbacae5abe5e23885899a1fa44253a17956c6d1c3...,0.0,49.0,1,0,0,0
1,0000423b00ade91418cceaf3b26c6af3dd342b51fd051e...,0.0,25.0,1,0,0,0
2,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,0.0,24.0,1,0,0,0
3,00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2...,0.0,54.0,1,0,0,0
4,00006413d8573cd20ed7128e53b7b13819fe5cfc2d801f...,1.0,52.0,1,0,0,0
...,...,...,...,...,...,...,...
1371975,ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e474...,0.0,24.0,1,0,0,0
1371976,ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab5...,0.0,21.0,1,0,0,0
1371977,ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1...,1.0,21.0,1,0,0,0
1371978,ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38...,1.0,18.0,1,0,0,0
1371979,ffffd9ac14e89946416d80e791d064701994755c3ab686...,0.0,65.0,0,0,0,1

# Transactions Data Exploration

In [177]:
df_transaction = pd.read_csv('transactions_train.csv')

In [89]:
df_transaction = df_transaction.sort_values("customer_id")

## Converting t-dat to Datetime in Transactions Dataset

In [178]:
df_transaction["t_dat"] = pd.to_datetime(df_transaction["t_dat"])

## Merging Tranactions with Articles

In [179]:
df_combined = df_transaction.merge(df_art, on=["article_id"], how="inner")
df_combined

,t_dat,customer_id,article_id,price,sales_channel_id,perceived_colour_value_name,index_group_name,modified_graphical_appearance,modified_product_group,modified_section,modified_garment_group,modified_product_type
0,2018-09-20,000058a12d5b43e67d225668fa1f8d618c13dc232df0ca...,663713001,0.050831,2,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
1,2018-09-20,3681748607f3287d2c3a65e00bb5fb153de30e9becf158...,663713001,0.049475,2,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
2,2018-09-20,4ef5967ff17bf474bffebe5b16bd54878e1d4105f7b4ed...,663713001,0.050831,2,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
3,2018-09-20,6b7b10d2d47516c82a6f97332478dab748070f09693f09...,663713001,0.050831,1,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
4,2018-09-20,8ac137752bbe914aa4ae6ad007a9a0c5b67a1ab2b2d474...,663713001,0.050831,2,Dark,Ladieswear,Solid,Underwear,Womens Lingerie,"Under-, Nightwear",other
...,...,...,...,...,...,...,...,...,...,...,...,...
31788319,2020-09-22,ec794d6268ee3c75b5bbea014e3299d994bcd1180ecf6d...,860135008,0.038119,1,Medium Dusty,Menswear,Check,Garment Upper body,other,other,Shirt
31788320,2020-09-22,ec794d6268ee3c75b5bbea014e3299d994bcd1180ecf6d...,539060028,0.016017,1,Bright,Baby/Children,All over pattern,Garment Upper body,other,Jersey Basic,Hoodie
31788321,2020-09-22,ec794d6268ee3c75b5bbea014e3299d994bcd1180ecf6d...,539060028,0.016000,1,Bright,Baby/Children,All over pattern,Garment Upper body,other,Jersey Basic,Hoodie
31788322,2020-09-22,ee9c048de16034be4aa95c91adce7f7bda442e6528406e...,810737015,0.033881,2,Light,Baby/Children,Front print,other,Baby Essentials & Complements,"Under-, Nightwear",other
31788323,2020-09-22,f79e372e21c1359dfebc7da0bf7f321d55e47b3275c351...,533261032,0.033881,2,Medium Dusty,Baby/Children,Solid,Garment Upper body,Baby Essentials & Complements,Jersey Basic,other

In [94]:
# for each customer find a random date to base the data point from
random_time = df_combined[df_combined.t_dat < "2020-09-15"].groupby("customer_id").agg({"t_dat": lambda x: x.sample(1)})

In [95]:
random_time.head()

                                                        t_dat
customer_id
32fe1032067fe86fe454716524146fe7947caa7608414f1... 2019-01-13
32fe148504dced0d743692fa2c0cd168990b6a9f20ba756... 2019-03-09
32fe25f404af8b953793e20adaf10f34762017802688339... 2019-05-02
32fe26fab07dd13b5f55393b32a2d5d01fad69dba11e7ca... 2019-11-03
32fe2d246a9806e85c00b22681ed61b2126ad36caee379e... 2020-06-08

In [96]:
random_time = random_time.rename(columns={"t_dat": "pivot"}).reset_index()

## Merging Pivot Dates with Combined (Transaction+Articles) Dataset

In [97]:
df_combined_random = df_combined.merge(random_time, on="customer_id")

In [98]:
df_combined_random.head()

,t_dat,customer_id,article_id,price,sales_channel_id,perceived_colour_value_name,index_group_name,modified_graphical_appearance,modified_product_group,modified_section,modified_garment_group,modified_product_type,pivot
0,2019-06-26,32fe1032067fe86fe454716524146fe7947caa7608414f...,408875002,0.006763,2,Dusty Light,Divided,Melange,Garment Upper body,other,Jersey Basic,Vest top,2019-01-13
1,2018-09-30,32fe1032067fe86fe454716524146fe7947caa7608414f...,572280002,0.007610,2,Dark,Baby/Children,Front print,Garment Upper body,Young Girl,Jersey Fancy,Sweater,2019-01-13
2,2019-06-26,32fe1032067fe86fe454716524146fe7947caa7608414f...,612481002,0.023712,2,Medium Dusty,Ladieswear,Denim,Garment Lower body,Womens Everyday Collection,other,Shorts,2019-01-13
3,2020-02-06,32fe1032067fe86fe454716524146fe7947caa7608414f...,706016001,0.029254,2,Dark,Divided,Solid,Garment Lower body,Divided Collection,Trousers,Trousers,2019-01-13
4,2020-03-27,32fe1032067fe86fe454716524146fe7947caa7608414f...,673396002,0.013542,2,Dark,Ladieswear,Solid,Accessories,other,Accessories,other,2019-01-13

In [99]:
# converting sales channel id to text to be able to do the one hot encoding
df_combined_random.sales_channel_id = df_combined_random.sales_channel_id.astype(str)

In [100]:
# columns that are used to featurize the clients
feature_columns = ["sales_channel_id", "perceived_colour_value_name",
            "index_group_name", "modified_graphical_appearance",
            "modified_product_group", "modified_section", "modified_garment_group",
            "modified_product_type"
           ]
# Forming the names of columns after one-hot-encoding
dummy_cols = []
for col in feature_columns:
    dummy_cols.extend([col + "_" + x for x in df_combined_random[col].unique()])
all_article_ids = list(df_article.article_id.unique())

In [101]:
# for each customer look at the transactions before the pivot time and find the characteristics of those transactions to
# get an understanding of what the customer likes, for example, what fraction of the articles the customer bought are
# dark. Then look at the 7 day period after the pivot time and consider the articles that the customer bought as positive
# target and sample randomly some articles that the customer never bought in their history as negative targets. Sample
# as many negative targets as there are positive ones
from random import sample

def process(df):
    before = df[df["t_dat"] <= df["pivot"]]
    before_7d = df[(df["t_dat"] <= df["pivot"]) & (df["t_dat"] > df["pivot"] - pd.Timedelta(7, "days"))]
    after = df[(df["t_dat"] > df["pivot"]) & (df["t_dat"] < df["pivot"] + pd.Timedelta(7, "days"))]
    after["label"] = 1
    after = after[["article_id", "label"]]
    if len(after) == 0:
        return None
    negs = sample(all_article_ids,len(after))
    negs = [i for i in negs if i not in df.article_id]
    negs_df = after.copy()
    negs_df["article_id"] = negs
    negs_df["label"] = 0
    after = pd.concat([after, negs_df], axis=0)
    means = pd.get_dummies(before[feature_columns]).mean(axis=0)
    means["avg_price"] = before["price"].mean()
    means_df = means.to_frame().transpose()
    means_df = means_df.reindex(columns=dummy_cols).fillna(0.0)
    means_df["num_purchase"] = len(before)
    # 7d calculations
    means_7d = pd.get_dummies(before_7d[feature_columns]).mean(axis=0)
    means_df_7d = means_7d.to_frame().transpose()
    means_df_7d.columns = means_df_7d.columns + "_7d"
    means_df_7d = means_df_7d.reindex(columns=[col + "_7d" for col in dummy_cols]).fillna(0.0)
    means_df_7d["num_purchase_7d"] = len(before_7d)
    means_df_7d["avg_price_7d"] = before_7d["price"].mean()
    means_df_combined = pd.concat([means_df, means_df_7d.fillna(0)], axis=1)
    combined = pd.concat([means_df_combined] * len(after), axis=0)
    combined["article_id"] = after["article_id"].values
    combined["label"] = after["label"].values
    
    return combined.reset_index(drop=True)

In [102]:
final_data = df_combined_random.groupby("customer_id").apply(process).reset_index(level=1, drop=True).reset_index()

In [113]:
one_hot_article = pd.get_dummies(df_article[feature_columns[1:]])

In [114]:
one_hot_article["article_id"] = df_article["article_id"]
one_hot_article.columns = one_hot_article.columns + "_target"

In [131]:
final_data_ = final_data.merge(df_cust, on="customer_id").merge(one_hot_article, left_on="article_id", right_on="article_id_target")

In [132]:
final_data_ = final_data_.drop(columns=["article_id_target", "article_id"])

In [545]:
final_data_.head()

,customer_id,sales_channel_id_1,sales_channel_id_2,perceived_colour_value_name_Dark,perceived_colour_value_name_MediumDusty,perceived_colour_value_name_DustyLight,perceived_colour_value_name_Bright,perceived_colour_value_name_Light,perceived_colour_value_name_Medium,perceived_colour_value_name_Unknown,...,modified_product_type_Skirt_target,modified_product_type_Sneakers_target,modified_product_type_Socks_target,modified_product_type_Sweater_target,modified_product_type_Tshirt_target,modified_product_type_Top_target,modified_product_type_Trousers_target,modified_product_type_Underwearbottom_target,modified_product_type_Vesttop_target,modified_product_type_other_target
0,0000d6c053fc8f9389d4565051f12402d5774aa4a9d2e5...,0.000000,1.000000,0.333333,0.500000,0.000000,0.000000,0.166667,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
1,001b9b6b1b2e37a2c24370041b884c99e14b3611693db1...,0.000000,1.000000,0.500000,0.000000,0.166667,0.000000,0.333333,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
2,026deff8ade4058f7709f5a4d3640beccfec2076ea2fd1...,0.100000,0.900000,0.600000,0.000000,0.200000,0.200000,0.000000,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
3,04d8c6e1c8aef3aad8eb2f33d9fcb74faeaf22799eaf32...,0.000000,1.000000,0.428571,0.142857,0.142857,0.071429,0.214286,0.000000,0.0,...,0,0,0,0,0,0,0,0,0,0
4,0583f24e7af774461ab00bb3292fc4bf36d94909022e07...,0.166667,0.833333,0.500000,0.000000,0.000000,0.000000,0.333333,0.166667,0.0,...,0,0,0,0,0,0,0,0,0,0

## Training

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.metrics import accuracy_score

In [141]:
import re
final_data_ = final_data_.rename(columns = lambda x:re.sub('[^A-Za-z0-9_]+', '', x))

### split data

In [142]:
X = final_data_.drop(columns=["label", "customer_id"])
y = final_data_["label"]
X_tr, X_val, y_tr, y_val = train_test_split(X, y, test_size=0.2)

First try bagging classifer

In [314]:
model1 = BaggingClassifier(DecisionTreeClassifier())
model1.fit(X_tr, y_tr)

BaggingClassifier(base_estimator=DecisionTreeClassifier())

In [315]:
accuracy_score(y_val, model1.predict(X_val))

0.7841474046323131

Good accuracy!

In [316]:
%%timeit
model1.predict(X_val)

2.06 s ± 15 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

But running it on the test data takes a lot of time!

In [137]:
import lightgbm as lgb

In [547]:
model = lgb.LGBMClassifier(learning_rate=0.09,max_depth=-5,n_estimators=1000, num_leaves=70)
model.fit(X_tr, y_tr, eval_set=[(X_val,y_val),(X_tr,y_tr)],
          verbose=20,eval_metric=["binary_error"])

[20]	training's binary_error: 0.24662	training's binary_logloss: 0.509179	valid_0's binary_error: 0.246996	valid_0's binary_logloss: 0.508656
[40]	training's binary_error: 0.233897	training's binary_logloss: 0.478009	valid_0's binary_error: 0.23571	valid_0's binary_logloss: 0.478567
[60]	training's binary_error: 0.226464	training's binary_logloss: 0.464	valid_0's binary_error: 0.228894	valid_0's binary_logloss: 0.465894
[80]	training's binary_error: 0.220875	training's binary_logloss: 0.454233	valid_0's binary_error: 0.222962	valid_0's binary_logloss: 0.457519
[100]	training's binary_error: 0.216768	training's binary_logloss: 0.447434	valid_0's binary_error: 0.220689	valid_0's binary_logloss: 0.452243
[120]	training's binary_error: 0.214353	training's binary_logloss: 0.443103	valid_0's binary_error: 0.219357	valid_0's binary_logloss: 0.449511
[140]	training's binary_error: 0.211693	training's binary_logloss: 0.439298	valid_0's binary_error: 0.217773	valid_0's binary_logloss: 0.447336
[160]	training's binary_error: 0.209275	training's binary_logloss: 0.435872	valid_0's binary_error: 0.216459	valid_0's binary_logloss: 0.445452
[180]	training's binary_error: 0.206894	training's binary_logloss: 0.432678	valid_0's binary_error: 0.21547	valid_0's binary_logloss: 0.443798
[200]	training's binary_error: 0.205074	training's binary_logloss: 0.430041	valid_0's binary_error: 0.214498	valid_0's binary_logloss: 0.442633
[220]	training's binary_error: 0.203134	training's binary_logloss: 0.427262	valid_0's binary_error: 0.213661	valid_0's binary_logloss: 0.441276
[240]	training's binary_error: 0.201136	training's binary_logloss: 0.424418	valid_0's binary_error: 0.212966	valid_0's binary_logloss: 0.4399
[260]	training's binary_error: 0.199333	training's binary_logloss: 0.421609	valid_0's binary_error: 0.212418	valid_0's binary_logloss: 0.438498
[280]	training's binary_error: 0.197644	training's binary_logloss: 0.419259	valid_0's binary_error: 0.211735	valid_0's binary_logloss: 0.437475
[300]	training's binary_error: 0.195401	training's binary_logloss: 0.41652	valid_0's binary_error: 0.21091	valid_0's binary_logloss: 0.436186
[320]	training's binary_error: 0.193892	training's binary_logloss: 0.414489	valid_0's binary_error: 0.210221	valid_0's binary_logloss: 0.435491
[340]	training's binary_error: 0.19208	training's binary_logloss: 0.411882	valid_0's binary_error: 0.209473	valid_0's binary_logloss: 0.434254
[360]	training's binary_error: 0.190577	training's binary_logloss: 0.409547	valid_0's binary_error: 0.209126	valid_0's binary_logloss: 0.433166
[380]	training's binary_error: 0.189265	training's binary_logloss: 0.407427	valid_0's binary_error: 0.208625	valid_0's binary_logloss: 0.432338
[400]	training's binary_error: 0.187683	training's binary_logloss: 0.405189	valid_0's binary_error: 0.208054	valid_0's binary_logloss: 0.431481
[420]	training's binary_error: 0.186163	training's binary_logloss: 0.403139	valid_0's binary_error: 0.207282	valid_0's binary_logloss: 0.430732
[440]	training's binary_error: 0.185097	training's binary_logloss: 0.401436	valid_0's binary_error: 0.207241	valid_0's binary_logloss: 0.430298
[460]	training's binary_error: 0.183633	training's binary_logloss: 0.399288	valid_0's binary_error: 0.206799	valid_0's binary_logloss: 0.429396
[480]	training's binary_error: 0.181959	training's binary_logloss: 0.396995	valid_0's binary_error: 0.206068	valid_0's binary_logloss: 0.42845
[500]	training's binary_error: 0.180402	training's binary_logloss: 0.394755	valid_0's binary_error: 0.205715	valid_0's binary_logloss: 0.427625
[520]	training's binary_error: 0.179039	training's binary_logloss: 0.392929	valid_0's binary_error: 0.205208	valid_0's binary_logloss: 0.426998
[540]	training's binary_error: 0.177435	training's binary_logloss: 0.390766	valid_0's binary_error: 0.204466	valid_0's binary_logloss: 0.426232
[560]	training's binary_error: 0.176094	training's binary_logloss: 0.388798	valid_0's binary_error: 0.203977	valid_0's binary_logloss: 0.425596
[580]	training's binary_error: 0.175017	training's binary_logloss: 0.387246	valid_0's binary_error: 0.203589	valid_0's binary_logloss: 0.425206
[600]	training's binary_error: 0.173689	training's binary_logloss: 0.385378	valid_0's binary_error: 0.20327	valid_0's binary_logloss: 0.424564
[620]	training's binary_error: 0.172646	training's binary_logloss: 0.383798	valid_0's binary_error: 0.202952	valid_0's binary_logloss: 0.424121
[640]	training's binary_error: 0.171478	training's binary_logloss: 0.382148	valid_0's binary_error: 0.202575	valid_0's binary_logloss: 0.423692
[660]	training's binary_error: 0.170344	training's binary_logloss: 0.380472	valid_0's binary_error: 0.202334	valid_0's binary_logloss: 0.423242
[680]	training's binary_error: 0.169073	training's binary_logloss: 0.378805	valid_0's binary_error: 0.20211	valid_0's binary_logloss: 0.422796
[700]	training's binary_error: 0.167959	training's binary_logloss: 0.377054	valid_0's binary_error: 0.201951	valid_0's binary_logloss: 0.422232
[720]	training's binary_error: 0.166716	training's binary_logloss: 0.375306	valid_0's binary_error: 0.201544	valid_0's binary_logloss: 0.42173
[740]	training's binary_error: 0.165572	training's binary_logloss: 0.373759	valid_0's binary_error: 0.201332	valid_0's binary_logloss: 0.421344
[760]	training's binary_error: 0.16427	training's binary_logloss: 0.37212	valid_0's binary_error: 0.201191	valid_0's binary_logloss: 0.420865
[780]	training's binary_error: 0.163148	training's binary_logloss: 0.370471	valid_0's binary_error: 0.200808	valid_0's binary_logloss: 0.42034
[800]	training's binary_error: 0.162081	training's binary_logloss: 0.368916	valid_0's binary_error: 0.200602	valid_0's binary_logloss: 0.419938
[820]	training's binary_error: 0.160977	training's binary_logloss: 0.367577	valid_0's binary_error: 0.200284	valid_0's binary_logloss: 0.419682
[840]	training's binary_error: 0.159837	training's binary_logloss: 0.365916	valid_0's binary_error: 0.200119	valid_0's binary_logloss: 0.419237
[860]	training's binary_error: 0.158777	training's binary_logloss: 0.364289	valid_0's binary_error: 0.200084	valid_0's binary_logloss: 0.418707
[880]	training's binary_error: 0.157855	training's binary_logloss: 0.363056	valid_0's binary_error: 0.199819	valid_0's binary_logloss: 0.418403
[900]	training's binary_error: 0.156745	training's binary_logloss: 0.36143	valid_0's binary_error: 0.199677	valid_0's binary_logloss: 0.417872
[920]	training's binary_error: 0.15565	training's binary_logloss: 0.359895	valid_0's binary_error: 0.199306	valid_0's binary_logloss: 0.417446
[940]	training's binary_error: 0.154578	training's binary_logloss: 0.358533	valid_0's binary_error: 0.199112	valid_0's binary_logloss: 0.417122
[960]	training's binary_error: 0.153556	training's binary_logloss: 0.357071	valid_0's binary_error: 0.198882	valid_0's binary_logloss: 0.416793
[980]	training's binary_error: 0.152525	training's binary_logloss: 0.355616	valid_0's binary_error: 0.198623	valid_0's binary_logloss: 0.416438
[1000]	training's binary_error: 0.151462	training's binary_logloss: 0.354225	valid_0's binary_error: 0.198582	valid_0's binary_logloss: 0.416217

LGBMClassifier(learning_rate=0.09, max_depth=-5, n_estimators=1000,
               num_leaves=70)

Model valid error rate is good 0.198 which is equal to around 80% accuracy

In [328]:
%%timeit
model.predict(X_val)

670 ms ± 47.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

Still very slow!

## Let's try Neural Networks

In [546]:
import pytorch_lightning as pl
import torch
from torch import nn
from torch.nn import functional as F
from torch.utils.data import DataLoader, Dataset

In [461]:
# In this network we pass the customer features through 2 layers and the article features through another 2 layers
# at the end, we dot product the resulting customer and article representation together
class Model(pl.LightningModule):
    def __init__(self, customer_dim, article_dim, hidden_dim):
        super(Model, self).__init__()
        self.customer_layer1 = torch.nn.Linear(customer_dim, hidden_dim)
        self.customer_layer2 = torch.nn.Linear(hidden_dim, hidden_dim)
        self.article_layer1 = torch.nn.Linear(article_dim, hidden_dim)
        self.article_layer2 = torch.nn.Linear(hidden_dim, hidden_dim)
    def forward(self, x, article_features):
        x = self.customer_layer2(F.relu(self.customer_layer1(x)))
        y = self.article_layer2(F.relu(self.article_layer1(article_features)))
        return (x * y).sum(-1)

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer

    def training_step(self, train_batch, batch_idx):
        x, z, y = train_batch
        loss = F.binary_cross_entropy_with_logits(self.forward(x, z), y)
        self.log('train_loss', loss)
        return loss

    def validation_step(self, val_batch, batch_idx):
        x, z, y = val_batch
        loss = F.binary_cross_entropy_with_logits(self.forward(x, z), y)
        self.log('val_loss', loss, on_epoch=True, on_step=False, prog_bar=True)

In [462]:
# Dataset needed for training
class dataset(Dataset):
    def __init__(self, features, labels, num_customer_features):
        self.customer_features = torch.tensor(features[:, :num_customer_features], dtype=torch.float32)
        self.article_features = torch.tensor(features[:, num_customer_features:], dtype=torch.float32)
        self.labels = torch.tensor(labels, dtype=torch.float32)
    def __len__(self):
        return len(self.customer_features)
    def __getitem__(self, i):
        return self.customer_features[i, :], self.article_features[i, :], self.labels[i]

train_set = dataset(X_tr.values, y_tr.values, 151)
val_set = dataset(X_val.values, y_val.values, 151)
train_loader = DataLoader(train_set, batch_size=32, num_workers=16, shuffle=True)
val_loader = DataLoader(val_set, batch_size=32, num_workers=16)

In [466]:
# model
model = Model(151, 69, 50)

# training
trainer = pl.Trainer(gpus=0, max_epochs=4)
trainer.fit(model, train_loader, val_loader)

GPU available: False, used: False
TPU available: None, using: 0 TPU cores

  | Name            | Type   | Params
-------------------------------------------
0 | customer_layer1 | Linear | 7.6 K
1 | customer_layer2 | Linear | 2.6 K
2 | article_layer1  | Linear | 3.5 K
3 | article_layer2  | Linear | 2.6 K
-------------------------------------------
16.2 K    Trainable params
0         Non-trainable params
16.2 K    Total params

HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Validation sanity check', layout=Layout…

HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Training', layout=Layout(flex='2'), max…

HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Validating', layout=Layout(flex='2'), m…

HBox(children=(FloatProgress(value=1.0, bar_style='info', description='Validating', layout=Layout(flex='2'), m…

1

In [467]:
accuracy_score(y_val, model(a, b) > 0)

0.7705049362644613

Not a bad accuracy